### PR TITLE
Ready

### PR DESCRIPTION
**Pull request by ddddavis**
Fixed no files, showing up.

### CODE REVIEW

**Comment by ddddavis** [comment]
Here is the previous pull request https://github.com/davisdambis/Embedding-Images-and-Video/pull/5

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @davisdambis @BrittanyBlake 
Your project looks good guys 👏👏.
However, there are a couple of things that you need to fix.

**Navigation bar**
- It should have a `<button>` tag that represents the search button but you have an image, see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/search_button_requirement.png)

**Video**
- It should have like and dislikes icons, yours are images, see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_like_requirement.png)
- It should have a share button, change it from image to a button, see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png)
- You have a subscribe image but It should be a subscribe button,  see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png).


**Additional Microverse Requirements (Pathwright)**

- Update your pull request's description with what you have implemented so far, see [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Kindly make the suggested changes and request for another code review
## Status: Changes Required
_Feel free to reach out to me on slack (fatima) if you have any questions, I'd be happy to help_

**Comment by ddddavis** [comment]
-Changed images to icons
-Added buttons to subscribe, share and search

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review by Tolulope Olusakin(TSE)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Fantastic job so far! @BrittanyBlake and @davisdambis 
You have both done some really impressive work, please consider the following comments I've left below and make appropriate changes to your project :100:.

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can and even include a link to the live project to speed up your review!

#### Navigation bar
Your navigation bar is a little buggy, the positioning of elements, and padding of the navigation are in a little twist. Consider comparing what the original site looks like(including but not limited to positioning, sizing of various elements, paddings and margins if there are) to yours and make any appropriate changes. Please see the requirement below.
screenshot

#### Recommended videos
Your recommended videos section has a lot of potential and needs just a little bit of polish to give it that shine! I think it is too much to the right and needs a bit more breathing space. Also, not that the text in this section are  all a bit squashed up and may also benefit from a reduced margin like I proposed above, however, do compare yours with the original site's and make appropriate changes as you see fit! :100: 

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

#### HTML Validation
Please condsider parsing your HTML markup through this validator and correct all resulting errors. It is mandatory that your markup is free from semantic or syntax errors.
screenshot

#### No Stickler requirements
I really commend your efforts in attempting to setup stickler on your repository, while it is generally not required for this project, if you do want to use it please ensure you correctly set it up and fix all the errors it throws! :+1: 

### Summary
This is really great from you both! Please take my comments above into consideration, make appropriate changes and request another review :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by ddddavis** [comment]
- Fixed navigation bar
- Fixed validation errors
- Changed recommended videos sidebar
- Fixed stickler, so it actually works 
- Fixed the horizontal scroll

Live Demo here - https://rawcdn.githack.com/davisdambis/Embedding-Images-and-Video/c91cb04fc042b0e2f3efc0558cb8cfead61978e5/index.html

**Comment by ddddavis** [comment]
- Fixed stickler, so it actually ACTUALLY works.

**Review by suretrust — APPROVED** [review]
Hi team, :wave: 

### Great job thus far implementing TSEs' suggestions. :raised_hands: No deal breaker, let's get this merged. :+1: 

- [ ] `Optional nice to have`: Your navigation bar is overflowing on my screen, it'd be really nice if you could fix this.

navbar

_Good luck with your future projects and happy coding!_ :tada:

**Pull request merged**
